@startuml seq-uc01-medicao
title SEQ-UC01 — Registrar Medição de Reator
skinparam shadowing false

actor Sensor
participant "ReatorFacade" as RF
participant "MedicaoReator" as MR
participant "EventBus" as Bus
participant "AlarmeFacade" as AF
participant "AuditoriaSubscriber" as Aud
participant "RegistroAuditoria" as Reg

Sensor -> RF: receberLeitura(sensorId, valor)
RF -> MR: registrarMedicao(valor, sensor, timestamp)
RF -> Bus: publicar(MedicaoRegistrada)
Bus -> Aud: onEvento(MedicaoRegistrada)
Aud -> Reg: registrar(evento)
Bus -> AF: onEvento(MedicaoRegistrada)

@enduml
