@startuml seq-uc01-medicao
title SEQ-UC01 — Registrar Medição de Reator
skinparam shadowing false

actor Sensor
participant "ReatorFacade" as RF
participant "MedicaoReator" as MR
participant "ReatorRepository" as RR
participant "EventBus" as Bus
participant "AvaliadorLimiar" as AL
participant "AlarmeFacade" as AF
participant "AuditoriaSubscriber" as Aud

Sensor -> RF: receberLeitura(sensorId, valores)
RF -> MR: registrarMedicao(valor, sensor, timestamp)
RF -> RR: salvarMedicao(medicao)
RF -> Bus: publicar(MedicaoRegistrada)
Bus -> Aud: onEvento(MedicaoRegistrada)
Aud -> Aud: RegistroAuditoria.registrar(evento)
RF -> AL: avaliar(medicao, limiar)
AL --> RF: ResultadoAvaliacao
RF -> AF: processarAvaliacao(resultado)

@enduml
