CREATE TABLE papel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  descricao VARCHAR(160) NOT NULL
);

CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(160) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  senha_hash VARCHAR(100) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuario_papel (
  id_usuario BIGINT NOT NULL,
  id_papel BIGINT NOT NULL,
  PRIMARY KEY (id_usuario, id_papel),
  CONSTRAINT fk_usuario_papel_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id),
  CONSTRAINT fk_usuario_papel_papel FOREIGN KEY (id_papel) REFERENCES papel(id)
);

CREATE TABLE registro_autenticacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT,
  email_informado VARCHAR(160) NOT NULL,
  resultado VARCHAR(20) NOT NULL,
  registrado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_registro_autenticacao_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);

INSERT INTO papel (codigo, descricao) VALUES
  ('OPERADOR_REATOR', 'Opera a supervisão do reator e reconhece alarmes.'),
  ('SUPERVISAO_CENTRAL', 'Acompanha a visão consolidada e recebe alertas.'),
  ('GUARDA_ACESSO', 'Controla o acesso físico a áreas restritas (UC04).'),
  ('ADMINISTRADOR_SISTEMA', 'Configura parâmetros e administra usuários do sistema.');
