spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:./data/usina;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
